### ISSUE TITLE
Weird Device.AllowedMessages behaviour with TestDeviceManager

### ISSUE THREAD

**Issue by rezreal** [buttplugio/buttplug-js#92]
using `buttplug:0.6.0`
```
node --version
v8.1.3
npm --version
5.6.0

```

The following code:
```typescript
const server = new ButtplugServer();
const serverConnector = new ButtplugEmbeddedServerConnector();
const testDeviceManager = new TestDeviceManager();
server.AddDeviceManager(testDeviceManager);
serverConnector.Server = server;

testDeviceManager.ConnectLinearDevice();
testDeviceManager.ConnectVibrationDevice();

async function doit() {
  const buttplug = new ButtplugClient(buttplugName);
  buttplug.addListener('deviceadded', (d)=> console.info("messages", d.AllowedMessages));
  await buttplug.Connect(serverConnector);
  await buttplug.StartScanning();
}
doit();
```
produces the following output
```
messages [ '0', '1', '2' ]
messages [ '0', '1', '2' ]
```
When I comment out the `testDeviceManager.ConnectXXDevice();` calls (i.e delay the device registration until the StartScanning triggers it implicitly), I can see the expected output:
```
messages [ 'VibrateCmd', 'SingleMotorVibrateCmd', 'StopDeviceCmd' ]
messages [ 'LinearCmd', 'FleshlightLaunchFW12Cmd', 'StopDeviceCmd' ]
```
Not sure if that is a desired behaviour, just stumbled across it.

**Comment by qdot** [comment]
Wow, ok, this was a HUGE bug, thanks for pointing it out!

Right now, most uses of the buttplug-js server as via a browser using the embedded server, so WebBluetooth devices only. Since WebBluetooth device connections can't survive between server lifetimes, we do the initial RequestDeviceList request, but never get anything back.

The test code you posted does exactly that though. It creates a server, then adds devices to the server, THEN connects it. This means that the server creates a DeviceList message when it receives RequestDeviceList, and that's where the problem was.

The server's RequestDeviceList construction didn't get updated with the rest of the schema updates back in December 2017/January 2018, but as its almost never called, no one noticed. The REALLY weird part is that, since the DeviceInfo and DeviceInfoWithSpecifications classes have basically the same shape, Typescript apparently thought they were equivalent? I never got any type errors, everything has compiled fine for months, that logic branch is even marked as covered in tests. So that's somewhat worrisome.

Anyways, I've fixed message construction and added your test to our suite, so hopefully this won't happen again. Thanks again for the through bug report!
